name: Deployment to Production
on: [push]
jobs:
  build:
    name: Deployment Process
    runs-on: ubuntu-latest
    environment: Hetzner
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY_ED25519 }}
        port: ${{ secrets.PORT }}
        script: ./build-fe.sh
